@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Admin
boundary 修改商品界面 as inout
control 修改商品控制器 as ctrl
entity 数据层 as dao
database 商品信息存取 as db

Admin -> inout : 输入商品信息
Admin -> inout : 发出修改商品指令
inout -> ctrl : 传递商品信息
ctrl -> dao : 查询要添加的商品信息是否存在
dao <-> db : 查询数据库
dao -> ctrl : 返回查询结果

ctrl --> inout : 商品信息不存在
note right : 商品信息不存在不能修改
inout -> Admin : 提示修改失败
note right : 提示需要重新输入等

ctrl --> inout : 商品信息能够找到 传递商品信息
note right : 修改商品信息
inout -> Admin : 提示商品信息能够修改 输入修改字段
Admin -> inout : 输入修改字段
inout -> ctrl : 传递修改的商品信息
ctrl -> ctrl : 进行修改信息的校验
ctrl -> dao : 更新商品信息条目
dao <-> db : 更新数据库
ctrl -> inout : 提示修改完成
inout -> Admin : 向用户提示修改完成


@enduml