@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Admin
boundary 添加商品界面 as inout
control 添加商品控制器 as ctrl
entity 数据层 as dao
database 商品信息存取 as db

Admin -> inout : 输入商品信息
Admin -> inout : 发出添加商品指令
inout -> ctrl : 传递商品信息
ctrl -> ctrl : 校验商品信息是否合规
ctrl -> dao : 查询要添加的商品信息是否存在
dao <-> db : 查询数据库
dao -> ctrl : 返回查询结果

ctrl --> inout : 商品信息已经存在
note right : 商品信息重复不能添加
inout -> Admin : 提示添加失败
note right : 提示需要重新输入等

ctrl --> dao : 商品信息未找到
note right : 添加商品信息a
dao <-> db : 操作商品数据库
ctrl -> inout : 添加已经完成
inout -> Admin : 提示已经添加完成


@enduml