@startuml
'https://plantuml.com/use-case-diagram

':Main Admin: as Admin
left to right direction


actor User

package 商品管理系统{

package 数据存储系统{
    usecase (用户列表存取操作)
    usecase (商品列表存取操作)
    usecase (购买历史存取操作)
    usecase (购物车存取操作)
}

usecase 客户登录 as "客户登录
--
输入用户名和密码
密码验证
"


User --> (客户登录)
(客户登录) ..> (用户列表存取操作):<<include>>
User --> (客户注册)
(客户注册) ..> (用户列表存取操作):<<include>>
(客户登录) --> (客户退出)

(客户登录) --> (购物管理)
(客户登录) --> (客户密码管理)

(客户密码管理) <|-- (自行修改密码)
(客户密码管理) <|-- (系统发送邮件)

(客户密码管理) ..> (用户列表存取操作):<<include>>

(购物管理) --> (添加商品到购物车)
(购物管理) --> (将商品移除购物车)
(购物管理) --> (修改商品购买数量)
(购物管理) --> (商品的付款)
(购物管理) --> (查看购物历史)


(查看购物历史) ..> (购买历史存取操作):<<include>>
(添加商品到购物车) ..> (购物车存取操作):<<include>>
(将商品移除购物车) ..> (购物车存取操作):<<include>>
(修改商品购买数量) ..> (购物车存取操作):<<include>>
(商品的付款) ..> (购物车存取操作):<<include>>
(商品的付款) ..> (购买历史存取操作):<<include>>


}

'(登录) --> (输入用户名)

note bottom of User : This is a normal user


@enduml