@startuml
'https://plantuml.com/use-case-diagram

':Main Admin: as Admin
left to right direction

actor Admin
package 商品管理系统{

package 数据存储系统{
    usecase (用户列表存取操作)
    usecase (商品列表存取操作)
    usecase (购买历史存取操作)
    usecase (购物车存取操作)
}

Admin --> (管理员登录)
(管理员登录) ..> (用户列表存取操作):<<include>>

(管理员登录) --> (客户管理)
(管理员登录) --> (管理员密码管理)
(管理员登录) --> (商品管理)
(管理员登录) -->  (退出)

(管理员密码管理) <|-- (修改管理员密码)
(管理员密码管理) <|-- (重置指定客户的密码)
(管理员密码管理) ..> (用户列表存取操作):<<include>>

(客户管理) <|-- (列出所有客户的信息)
(客户管理) <|-- (删除客户的信息)
(客户管理) <|-- (查询客户的信息)
(客户管理) ..> (用户列表存取操作):<<include>>
(查询客户的信息) ..> (购买历史存取操作):<<include>>

(商品管理) --> (列出商品信息)
(商品管理) --> (修改商品信息)
(商品管理) --> (删除商品信息)
(商品管理) --> (添加商品信息)
(列出商品信息) ..> (商品列表存取操作):<<include>>
(修改商品信息) ..> (商品列表存取操作):<<include>>
(删除商品信息) ..> (商品列表存取操作):<<include>>
(添加商品信息) ..> (商品列表存取操作):<<include>>


}

'(登录) --> (输入用户名)



note bottom of Admin : 这是整个系统的管理员


@enduml